### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by batelis123** [baldwin-agency/magento2-module-url-data-integrity-checker#36] opened 2022-05-17 09:22 UTC
![image](https://user-images.githubusercontent.com/105712094/168777402-3a53aec9-9871-480b-89aa-7a148be47189.png)

**Comment by hostep** [comment] 2022-05-17 09:44
Hi @batelis123: do you have some more info?

What version of the module are you using? What version of Magento are you using? What path is entered in this config value: Stores > Configuration > Catalog > Url Data Integrity Checker > Path to store results?

I've spend a couple of minutes trying to reproduce but am unable to, so some more info would be appreciated, thanks! 🙂

**Comment by batelis123** [comment] 2022-05-17 09:48
Hi,
My magento version is 2.3.5-p1
module version is the last version

I just installed the module and try to enter to module pages.

I can see that the directory tmp is added but its empty.


Thank you

________________________________

**Comment by hostep** [comment] 2022-05-17 10:15
Hmm, just installed version 1.4.0 of this module on a clean Magento 2.3.5-p1 install and I'm not able to reproduce the problem.

Just to be sure, is the following field `Stores > Configuration > Catalog > Url Data Integrity Checker > Path to store results` empty in the backoffice?

Any specific environment settings that could potentially cause this problem? Permission problems maybe?

The strange thing, is that the code in your stacktrace [throws a `FileSystemException`](https://github.com/magento/magento2/blob/2.3.5-p1/lib/internal/Magento/Framework/Filesystem/Driver/File.php#L151-L156) and we [catch that type of exception](https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/blob/v1.4.0/Storage/FileStorage.php#L67), so I'm really unsure about what is going on on your system... 😕 

Maybe you can try to debug a little bit to try to figure out what's going on?

Maybe you can solve it by generating those reports using the command line and then maybe the backoffice grids will no longer crash?
```bash
bin/magento catalog:category:integrity:urlkey
bin/magento catalog:category:integrity:urlpath
bin/magento catalog:product:integrity:urlkey
bin/magento catalog:product:integrity:urlpath
```

**Comment by batelis123** [comment] 2022-05-17 12:35
OK
Just after run the cli commands the pages are load and there are no errors.

Thank you
________________________________

**Comment by hostep** [comment] 2022-05-17 12:41
Okay good to hear! I'll close this issue now.

In case you run into it again in the future, and can maybe debug a little bit to see how this triggers, that would be really helpful, but don't feel obligated to do this 🙂

**Closed as completed by hostep** 2022-05-17 12:41 UTC
