### ISSUE TITLE
CLI commands do not work on Magento 2.4.1

### ISSUE THREAD

**Issue by kamephis** [baldwin-agency/magento2-module-url-data-integrity-checker#22] opened 2021-03-17 10:31 UTC
Wether using the cli or the admin menu entry does not work on Magento 2.4.1 CE

`There are no commands defined in the "catalog:category:integrity" namespace.
Did you mean this?
wyomind:dynamiccategory
`

In the magento backend you're redirected to the dashboard.
`Invalid security or form key. Please refresh the page.
`

**Comment by hostep** [comment] 2021-03-22 16:46
Hi @kamephis, I haven't experienced this problem yet and tested the module on Magento 2.4.0 and 2.4.2.

Have you maybe already found some more info about this problem in the mean while? Because right now it's not clear to me yet how to reproduce the problem.

The problems that most people run against with this module has often to do with 3rd party modules our customisations done to their shop that somehow conflict with this module. Could you maybe try to disable all non-default Magento modules and retry using this module? If that works, it means one or more of those modules you disabled somehow cause a conflict. If you could figure out which module it is exactly that might get us closer to finding a solution.

**Comment by DominicWatts** [comment] 2021-08-21 00:32
Confirmed working on 2.4.2

**Comment by hostep** [comment] 2021-09-26 18:34
Closing issue, since I've received no reaction yet. Feel free to comment on this again if you have some more info around this problem. Thanks!

**Closed as completed by hostep** 2021-09-26 18:34 UTC
